version: '3'
services:
    nginx:
        image: nginx
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./letsencrypt:/etc/letsencrypt:ro
            - http_challenge:/var/www/.well-known:ro
            - ./scripts:/scripts
            - ./config:/config
            - ./manual-configuration-files:/manual-configuration-files
            - /root/sites/static:/var/www/sites/static

        command: /bin/bash -c "/scripts/generate-config.sh && cp /manual-configuration-files/*.conf /etc/nginx/conf.d/ && exec nginx -g 'daemon off;'"

    certbot:
        image: certbot/certbot
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - http_challenge:/var/www/.well-known
            - ./scripts:/scripts
            - ./config:/config

        depends_on:
            - nginx
        entrypoint: sh -c
        command: certbot renew

volumes:
    http_challenge: ~
